#!/bin/bash
set -euo pipefail

tmpdir=$(mktemp -d)
cd "$tmpdir"

cargo new hello
cd hello

cat <<EOF > src/main.rs
use anyhow::Result;

fn main() -> Result<()> {
    println!("Hello, World!");
    Ok(())
}

#[test]
fn test() {
    assert_eq!(1 + 1, 2);
}
EOF

mkdir -p .cargo
cat <<EOF > .cargo/config.toml
[source.crates-io]
replace-with = "packaged-sources"

[source.packaged-sources]
directory = "/usr/share/cargo/registry"
EOF

cargo add 'anyhow@^1'

cargo check
cargo build
cargo test
cargo run
