#!/bin/bash
set -euo pipefail

tmpdir=$(mktemp -d)
cd "$tmpdir"

cargo new hello
cd hello

# this will only add the dependency to Cargo.toml
cargo add 'anyhow@^1'

# this will download, but not build `anyhow`
cargo vendor

# verify vendoring worked
find vendor/anyhow
